name: "Upload Docs to Azure Blob Storage"
on: 
  push: 
    branches: 
      - main
      - feature/documentation-site

jobs: 
  Build-Publish_Documentation: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      # Build
      - uses: Tiryoh/actions-mkdocs@v0
        with:
          requirements: 'docs/.requirements.txt'
      # Upload
      - uses: bacongobbler/azure-blob-storage-upload@main
        with: 
          container_name: $web
          extra_args: "--destination-path discordconnector.valheim.nwest.games/ --overwrite"
          connection_string: "${{ secrets.AZURE_CONNECTION_STRING }}"
          source_dir: bin/mkdocs
          sync: true

